# ------------------------------------------------------------------------------
#  randomforge — Innovating the Future of Randomization
#  Framework for transparent and extensible clinical trial randomization in R
#
#  Author: Friedrich Pahlke, RPACT GmbH
#  Copyright (c) 2025
#
#  This file is part of the randomforge R package.
#  The package is licensed under the GNU Lesser General Public License (LGPL-3.0).
#  Full license text: https://www.gnu.org/licenses/lgpl-3.0.txt
#
#  Source code and issue tracker:
#  https://github.com/RCONIS/randomforge
#
#  Documentation:
#  https://randomforge.org
#
#  For collaboration or contributions:
#  friedrich.pahlke@rpact.com
#  info@randomforge.org
# ------------------------------------------------------------------------------

test_that("Test that seed is working as expected", {
        
    randomAllocationValueService <- getRandomAllocationValueService()
    
    randomDataBase <- getRandomDataBase()
    
    randomProject <- getRandomProject(name = "Test")
    randomDataBase$persist(randomProject)
    
    randomConfiguration <- getRandomConfiguration(randomProject = randomProject, treatmentArmIds = c("A", "B"), seed = 2551171)
    randomDataBase$persist(randomConfiguration)
    
    blockSizes <- list()
    blockSizes[[1]] <- list("A" = 2, "B" = 2)
    blockSizes[[2]] <- list("A" = 3, "B" = 3)
    
    blockSizeRandomizer <- getRandomBlockSizeRandomizer(blockSizes, seed = 371022898L)
    randomMethod <- getRandomMethodPBR(
        blockSizes = blockSizes, 
        fixedBlockDesignEnabled = FALSE, 
        blockSizeRandomizer = blockSizeRandomizer)
    
    for (i in 1:30) {
        suppressMessages(temp <- getNextRandomResult(
            randomDataBase, 
            randomProject, 
            randomMethod, 
            randomAllocationValueService))
    }

    
    ## Comparison of the results of RandomProject object 'randomProject' with expected results
    expect_equal(randomProject$name, "Test")
    
    ## Comparison of the results of RandomConfiguration object 'randomConfiguration' with expected results
    expect_equal(randomConfiguration$seed, 2551171)
    expect_equal(randomConfiguration$ravBufferMinimumSize, 1000)
    expect_equal(randomConfiguration$randomProject$name, "Test")
    expect_equal(randomConfiguration$treatmentArmIds, c("A", "B"))
    expect_equal(randomConfiguration$ravBufferMaximumSize, 10000)
    
    ## Comparison of the results of RandomMethodPBR object 'randomMethod' with expected results
    expect_equal(randomMethod$fixedBlockDesignEnabled, FALSE)
    expect_equal(randomMethod$blockSizeRandomizer$seed, 371022898)
    expect_equal(randomMethod$blockSizeRandomizer$index, 7)
    expect_equal(randomMethod$blockSizeRandomizer$values, c(2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 2, 2))
    expect_equal(randomMethod$name, "PBR")
    expect_equal(randomMethod$fixedBlockIndex, 1)
    expect_equal(randomMethod$blockSizes[[1]]$A, 2)
    expect_equal(randomMethod$blockSizes[[1]]$B, 2)
    expect_equal(randomMethod$blockSizes[[2]]$A, 3)
    expect_equal(randomMethod$blockSizes[[2]]$B, 3)
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[1]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.005917588, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 1)
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 0)
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$randomSystemState$fillingLevelsOverall$A, 1)
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$randomSystemState$fillingLevelsOverall$B, 0)
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 1)
    expect_equal(randomDataBase$randomSubjects[[1]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 0)
    expect_equal(randomDataBase$randomSubjects[[1]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[1]]$randomNumber, 1)
    expect_equal(randomDataBase$randomSubjects[[1]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[2]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.50474443, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 1)
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 1)
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$randomSystemState$fillingLevelsOverall$A, 1)
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$randomSystemState$fillingLevelsOverall$B, 1)
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 1)
    expect_equal(randomDataBase$randomSubjects[[2]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 1)
    expect_equal(randomDataBase$randomSubjects[[2]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[2]]$randomNumber, 2)
    expect_equal(randomDataBase$randomSubjects[[2]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[3]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.13823, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 2)
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 1)
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$randomSystemState$fillingLevelsOverall$A, 2)
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$randomSystemState$fillingLevelsOverall$B, 1)
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 2)
    expect_equal(randomDataBase$randomSubjects[[3]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 1)
    expect_equal(randomDataBase$randomSubjects[[3]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[3]]$randomNumber, 3)
    expect_equal(randomDataBase$randomSubjects[[3]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[4]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.9719263, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 2)
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 2)
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$randomSystemState$fillingLevelsOverall$A, 2)
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$randomSystemState$fillingLevelsOverall$B, 2)
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 2)
    expect_equal(randomDataBase$randomSubjects[[4]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 2)
    expect_equal(randomDataBase$randomSubjects[[4]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[4]]$randomNumber, 4)
    expect_equal(randomDataBase$randomSubjects[[4]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[5]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.14295174, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 3)
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 2)
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$randomSystemState$fillingLevelsOverall$A, 3)
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$randomSystemState$fillingLevelsOverall$B, 2)
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[5]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 2)
    expect_equal(randomDataBase$randomSubjects[[5]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[5]]$randomNumber, 5)
    expect_equal(randomDataBase$randomSubjects[[5]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[6]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.22546695, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0)
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 3)
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 3)
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$randomSystemState$fillingLevelsOverall$A, 3)
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$randomSystemState$fillingLevelsOverall$B, 3)
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[6]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[6]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[6]]$randomNumber, 6)
    expect_equal(randomDataBase$randomSubjects[[6]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[7]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.61278524, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 0)
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 1)
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$randomSystemState$fillingLevelsOverall$A, 3)
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$randomSystemState$fillingLevelsOverall$B, 4)
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 0)
    expect_equal(randomDataBase$randomSubjects[[7]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 1)
    expect_equal(randomDataBase$randomSubjects[[7]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[7]]$randomNumber, 7)
    expect_equal(randomDataBase$randomSubjects[[7]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[8]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.59834207, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 0)
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 2)
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$randomSystemState$fillingLevelsOverall$A, 3)
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$randomSystemState$fillingLevelsOverall$B, 5)
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 0)
    expect_equal(randomDataBase$randomSubjects[[8]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 2)
    expect_equal(randomDataBase$randomSubjects[[8]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[8]]$randomNumber, 8)
    expect_equal(randomDataBase$randomSubjects[[8]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[9]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.095591015, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 1)
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 2)
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$randomSystemState$fillingLevelsOverall$A, 4)
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$randomSystemState$fillingLevelsOverall$B, 5)
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 1)
    expect_equal(randomDataBase$randomSubjects[[9]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 2)
    expect_equal(randomDataBase$randomSubjects[[9]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[9]]$randomNumber, 9)
    expect_equal(randomDataBase$randomSubjects[[9]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[10]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.38667627, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 2)
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 2)
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$randomSystemState$fillingLevelsOverall$A, 5)
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$randomSystemState$fillingLevelsOverall$B, 5)
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 2)
    expect_equal(randomDataBase$randomSubjects[[10]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 2)
    expect_equal(randomDataBase$randomSubjects[[10]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[10]]$randomNumber, 10)
    expect_equal(randomDataBase$randomSubjects[[10]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[11]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.69306033, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 2)
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 3)
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$randomSystemState$fillingLevelsOverall$A, 5)
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$randomSystemState$fillingLevelsOverall$B, 6)
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 2)
    expect_equal(randomDataBase$randomSubjects[[11]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[11]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[11]]$randomNumber, 11)
    expect_equal(randomDataBase$randomSubjects[[11]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[12]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.93837646, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 1)
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 3)
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 3)
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$randomSystemState$fillingLevelsOverall$A, 6)
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$randomSystemState$fillingLevelsOverall$B, 6)
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[12]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[12]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[12]]$randomNumber, 12)
    expect_equal(randomDataBase$randomSubjects[[12]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[13]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.79194056, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 2)
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 2)
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 0)
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 2)
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 1)
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 2)
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$randomSystemState$fillingLevelsOverall$A, 6)
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$randomSystemState$fillingLevelsOverall$B, 7)
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 0)
    expect_equal(randomDataBase$randomSubjects[[13]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 1)
    expect_equal(randomDataBase$randomSubjects[[13]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[13]]$randomNumber, 13)
    expect_equal(randomDataBase$randomSubjects[[13]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[14]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.076516353, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 2)
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 2)
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 1)
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 2)
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 1)
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 2)
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$randomSystemState$fillingLevelsOverall$A, 7)
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$randomSystemState$fillingLevelsOverall$B, 7)
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 1)
    expect_equal(randomDataBase$randomSubjects[[14]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 1)
    expect_equal(randomDataBase$randomSubjects[[14]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[14]]$randomNumber, 14)
    expect_equal(randomDataBase$randomSubjects[[14]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[15]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.97194517, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 2)
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 2)
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 1)
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 2)
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 2)
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 2)
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$randomSystemState$fillingLevelsOverall$A, 7)
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$randomSystemState$fillingLevelsOverall$B, 8)
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 1)
    expect_equal(randomDataBase$randomSubjects[[15]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 2)
    expect_equal(randomDataBase$randomSubjects[[15]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[15]]$randomNumber, 15)
    expect_equal(randomDataBase$randomSubjects[[15]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[16]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.89117019, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 1)
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 2)
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 2)
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 2)
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 2)
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 2)
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 2)
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$randomSystemState$fillingLevelsOverall$A, 8)
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$randomSystemState$fillingLevelsOverall$B, 8)
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 2)
    expect_equal(randomDataBase$randomSubjects[[16]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 2)
    expect_equal(randomDataBase$randomSubjects[[16]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[16]]$randomNumber, 16)
    expect_equal(randomDataBase$randomSubjects[[16]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[17]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.18272232, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 1)
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 0)
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$randomSystemState$fillingLevelsOverall$A, 9)
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$randomSystemState$fillingLevelsOverall$B, 8)
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 1)
    expect_equal(randomDataBase$randomSubjects[[17]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 0)
    expect_equal(randomDataBase$randomSubjects[[17]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[17]]$randomNumber, 17)
    expect_equal(randomDataBase$randomSubjects[[17]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[18]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.16037698, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 2)
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 0)
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$randomSystemState$fillingLevelsOverall$A, 10)
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$randomSystemState$fillingLevelsOverall$B, 8)
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 2)
    expect_equal(randomDataBase$randomSubjects[[18]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 0)
    expect_equal(randomDataBase$randomSubjects[[18]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[18]]$randomNumber, 18)
    expect_equal(randomDataBase$randomSubjects[[18]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[19]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.28430677, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 3)
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 0)
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$randomSystemState$fillingLevelsOverall$A, 11)
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$randomSystemState$fillingLevelsOverall$B, 8)
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[19]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 0)
    expect_equal(randomDataBase$randomSubjects[[19]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[19]]$randomNumber, 19)
    expect_equal(randomDataBase$randomSubjects[[19]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[20]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.91283932, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0)
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 3)
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 1)
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$randomSystemState$fillingLevelsOverall$A, 11)
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$randomSystemState$fillingLevelsOverall$B, 9)
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[20]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 1)
    expect_equal(randomDataBase$randomSubjects[[20]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[20]]$randomNumber, 20)
    expect_equal(randomDataBase$randomSubjects[[20]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[21]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.1989649, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0)
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 3)
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 2)
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$randomSystemState$fillingLevelsOverall$A, 11)
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$randomSystemState$fillingLevelsOverall$B, 10)
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[21]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 2)
    expect_equal(randomDataBase$randomSubjects[[21]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[21]]$randomNumber, 21)
    expect_equal(randomDataBase$randomSubjects[[21]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[22]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.11482143, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0)
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 3)
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 3)
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$randomSystemState$fillingLevelsOverall$A, 11)
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$randomSystemState$fillingLevelsOverall$B, 11)
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[22]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[22]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[22]]$randomNumber, 22)
    expect_equal(randomDataBase$randomSubjects[[22]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[23]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.92294517, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 0)
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 1)
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$randomSystemState$fillingLevelsOverall$A, 11)
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$randomSystemState$fillingLevelsOverall$B, 12)
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 0)
    expect_equal(randomDataBase$randomSubjects[[23]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 1)
    expect_equal(randomDataBase$randomSubjects[[23]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[23]]$randomNumber, 23)
    expect_equal(randomDataBase$randomSubjects[[23]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[24]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.23636891, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 1)
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 1)
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$randomSystemState$fillingLevelsOverall$A, 12)
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$randomSystemState$fillingLevelsOverall$B, 12)
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 1)
    expect_equal(randomDataBase$randomSubjects[[24]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 1)
    expect_equal(randomDataBase$randomSubjects[[24]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[24]]$randomNumber, 24)
    expect_equal(randomDataBase$randomSubjects[[24]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[25]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.32104056, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 2)
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 1)
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$randomSystemState$fillingLevelsOverall$A, 13)
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$randomSystemState$fillingLevelsOverall$B, 12)
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 2)
    expect_equal(randomDataBase$randomSubjects[[25]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 1)
    expect_equal(randomDataBase$randomSubjects[[25]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[25]]$randomNumber, 25)
    expect_equal(randomDataBase$randomSubjects[[25]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[26]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.21262875, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 3)
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 1)
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$randomSystemState$fillingLevelsOverall$A, 14)
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$randomSystemState$fillingLevelsOverall$B, 12)
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[26]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 1)
    expect_equal(randomDataBase$randomSubjects[[26]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[26]]$randomNumber, 26)
    expect_equal(randomDataBase$randomSubjects[[26]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[27]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.3372851, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0)
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 3)
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 2)
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$randomSystemState$fillingLevelsOverall$A, 14)
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$randomSystemState$fillingLevelsOverall$B, 13)
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[27]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 2)
    expect_equal(randomDataBase$randomSubjects[[27]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[27]]$randomNumber, 27)
    expect_equal(randomDataBase$randomSubjects[[27]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[28]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.40150169, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0)
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 3)
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 3)
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$randomSystemState$fillingLevelsOverall$A, 14)
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$randomSystemState$fillingLevelsOverall$B, 14)
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[28]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[28]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[28]]$randomNumber, 28)
    expect_equal(randomDataBase$randomSubjects[[28]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[29]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.32599302, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 1)
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 0)
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$randomSystemState$fillingLevelsOverall$A, 15)
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$randomSystemState$fillingLevelsOverall$B, 14)
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 1)
    expect_equal(randomDataBase$randomSubjects[[29]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 0)
    expect_equal(randomDataBase$randomSubjects[[29]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[29]]$randomNumber, 29)
    expect_equal(randomDataBase$randomSubjects[[29]]$randomProject$name, "Test")
    
    ## Comparison of the results of RandomSubject object 'randomDataBase$randomSubjects[[30]]' with expected results
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$randomMethodRangeSet$randomAllocationDoubleValue, 0.67302807, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$randomMethodRangeSet$ranges$A$upperBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$randomMethodRangeSet$ranges$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$randomMethodRangeSet$ranges$A$lowerBound, 0)
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$randomMethodRangeSet$ranges$B$upperBound, 1)
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$randomMethodRangeSet$ranges$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$randomMethodRangeSet$ranges$B$lowerBound, 0.5, tolerance = 1e-07)
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$A, 3)
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$randomSystemState$fillingLevelsBlockMaximum$NO_FACTOR_ID$B, 3)
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$treatmentArmId, "A")
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$currentSize, 1)
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$A$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$treatmentArmId, "B")
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$currentSize, 1)
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$enabled, TRUE)
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$randomSystemState$blocks$NO_FACTOR_ID$blockArms$B$maximumSize, 3)
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$randomSystemState$fillingLevelsOverall$A, 15)
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$randomSystemState$fillingLevelsOverall$B, 15)
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$A, 1)
    expect_equal(randomDataBase$randomSubjects[[30]]$randomResult$randomSystemState$fillingLevelsBlock$NO_FACTOR_ID$B, 1)
    expect_equal(randomDataBase$randomSubjects[[30]]$status, "RANDOMIZED")
    expect_equal(randomDataBase$randomSubjects[[30]]$randomNumber, 30)
    expect_equal(randomDataBase$randomSubjects[[30]]$randomProject$name, "Test")
    
})

